upstream php_backend {
    server app:9000;
}

server {
    listen 80;
    server_name _;
    charset utf-8;

    root /usr/share/nginx/html;
    index index.html;

    client_max_body_size 32m;

    location /storage/ {
        alias /var/www/backend/storage/app/public/;
        access_log off;
        expires 7d;
        try_files $uri =404;
    }

    location ~ ^/(api|sanctum|up)(/|$) {
        include fastcgi_params;
        fastcgi_pass php_backend;
        fastcgi_param SCRIPT_FILENAME /var/www/backend/public/index.php;
        fastcgi_param SCRIPT_NAME /index.php;
        fastcgi_param DOCUMENT_ROOT /var/www/backend/public;
        fastcgi_param QUERY_STRING $query_string;
        fastcgi_param REQUEST_URI $request_uri;
        fastcgi_param PATH_INFO "";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
