<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'id' => 1,
                'role_id' => 2,
                'filial_id' => 1,
                'rut' => '1234556',
                'nombre' => 'ejemplo',
                'email' => 'ejemplo@ejemplo.com',
                'telefono' => '93405665',
                'fecha_nacimiento' => '1993-01-16',
                'fecha_ingreso' => '2024-03-01',
                'grupo_sanguineo' => 'B',
                'factor_rh' => 'positivo',
                'password' => Hash::make('hola1234'),
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 2,
                'role_id' => 2,
                'filial_id' => 1,
                'rut' => '123456789',
                'nombre' => 'ejemplo1',
                'email' => 'ejemplo1@ejemplo.com',
                'telefono' => '94056655',
                'fecha_nacimiento' => '1994-07-16',
                'fecha_ingreso' => '2024-03-01',
                'grupo_sanguineo' => 'A',
                'factor_rh' => 'negativo',
                'password' => Hash::make('hola12345'),
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 3,
                'role_id' => 2,
                'filial_id' => 1,
                'rut' => '12345678910',
                'nombre' => 'ejemplo2',
                'email' => 'ejemplo2@ejemplo.com',
                'telefono' => '934056543',
                'fecha_nacimiento' => '1995-07-16',
                'fecha_ingreso' => '2025-03-01',
                'grupo_sanguineo' => 'O',
                'factor_rh' => 'positivo',
                'password' => Hash::make('hola4321'),
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 4,
                'role_id' => 2,
                'filial_id' => 1,
                'rut' => '10574072-2',
                'nombre' => 'Emilia',
                'email' => 'prueba@test.cl',
                'telefono' => '+56993594...',
                'fecha_nacimiento' => '1993-10-08',
                'fecha_ingreso' => '2020-02-20',
                'grupo_sanguineo' => 'B',
                'factor_rh' => '-',
                'password' => '$2y$12$T6djap1DMVWc7XEcplm59.OucY.Ddcn.ZOcL/Errnr7A.jp',
                'created_at' => '2025-04-21 14:00:16',
                'updated_at' => '2025-04-25 15:11:00',
            ],
            [
                'id' => 6,
                'role_id' => 2,
                'filial_id' => 1,
                'rut' => '1111111',
                'nombre' => 'ejemplo3',
                'email' => 'ejemplo3@ejemplo.com',
                'telefono' => '93406666',
                'fecha_nacimiento' => '1991-07-16',
                'fecha_ingreso' => '2021-03-01',
                'grupo_sanguineo' => 'B',
                'factor_rh' => 'positivo',
                'password' => Hash::make('hola12345754'),
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 28,
                'role_id' => 2,
                'filial_id' => 1,
                'rut' => '10.574.084-2',
                'nombre' => 'alejandro',
                'email' => 'modificado@modificado.cl',
                'telefono' => '+56993567...',
                'fecha_nacimiento' => '2000-06-26',
                'fecha_ingreso' => '2021-08-28',
                'grupo_sanguineo' => 'A',
                'factor_rh' => '-',
                'password' => '$2y$12$mQpaawoh1SE2p.aSyOaice5CsjW0U1CM6OBb/PP/37',
                'created_at' => '2025-04-21 14:05:08',
                'updated_at' => '2025-04-25 15:10:08',
            ],
            [
                'id' => 41,
                'role_id' => 2,
                'filial_id' => 1,
                'rut' => '15.456.789-0',
                'nombre' => 'Agustin',
                'email' => 'hola@hola.com',
                'telefono' => '+56993557...',
                'fecha_nacimiento' => '1997-10-28',
                'fecha_ingreso' => '2018-12-21',
                'grupo_sanguineo' => 'O',
                'factor_rh' => '+',
                'password' => '$2y$12$fyT4cRC9qRz1opbzu1abz.uClouLAe/v6yqM.lPgt.CPy',
                'created_at' => '2025-04-26 09:52:08',
                'updated_at' => '2025-04-25 15:10:50',
            ],
            [
                'id' => 49,
                'role_id' => 1,
                'filial_id' => 1,
                'rut' => '185740722',
                'nombre' => 'asdf',
                'email' => 'correr@ejemplo.com',
                'telefono' => '123',
                'fecha_nacimiento' => '1992-07-27',
                'fecha_ingreso' => '2021-02-26',
                'grupo_sanguineo' => 'O',
                'factor_rh' => '+',
                'password' => '$2y$12$TIGe8aPyfWUc4dciWGo.s.eCdeSfrU/iS6o8a.5T/W',
                'created_at' => '2025-04-29 02:43:24',
                'updated_at' => '2025-04-29 02:43:24',
            ],
            [
                'id' => 51,
                'role_id' => 2,
                'filial_id' => 1,
                'rut' => '1111111111',
                'nombre' => 'aaaaa',
                'email' => 'aaaaaa@ejemplo.com',
                'telefono' => 'xxxxxx',
                'fecha_nacimiento' => '2023-10-28',
                'fecha_ingreso' => '2023-02-04',
                'grupo_sanguineo' => 'O',
                'factor_rh' => '+',
                'password' => '$2y$12$08LT4j/e9wNShhNkXu1wx.CAPK/b.tSg.2zHDJcZEHWMxO',
                'created_at' => '2025-05-07 10:05:41',
                'updated_at' => '2025-05-07 10:06:41',
            ],
            [
                'id' => 56,
                'role_id' => 2,
                'filial_id' => 1,
                'rut' => '18574072-2',
                'nombre' => 'aaa',
                'email' => 'sakutwif@gmail.com',
                'telefono' => '233333',
                'fecha_nacimiento' => '2024-07-03',
                'fecha_ingreso' => '2025-05-08',
                'grupo_sanguineo' => 'O',
                'factor_rh' => '+',
                'password' => '$2y$12$K2oCiXh6PBRW.TgGdp1v.uCeAnM.oA/h.Gk/L7bBHnDe',
                'created_at' => '2025-05-07 13:14:31',
                'updated_at' => '2025-05-07 13:14:51',
            ],
        ]);
    }
}
